name: CI contracts tests
env:
  MATIC_ACCOUNT1: ${{ secrets.MATIC_ACCOUNT1 }}
  MATIC_ACCOUNT2: ${{ secrets.MATIC_ACCOUNT2 }}
  MATIC_ACCOUNT3: ${{ secrets.MATIC_ACCOUNT3 }}
  HARDHAT_ACCOUNT1: ${{ secrets.HARDHAT_ACCOUNT1 }}
  HARDHAT_ACCOUNT2: ${{ secrets.HARDHAT_ACCOUNT2 }}
  HARDHAT_ACCOUNT3: ${{ secrets.HARDHAT_ACCOUNT3 }}
  AUDIO_URI: ${{ secrets.AUDIO_URI }}
  IMAGE_URI1: ${{ secrets.IMAGE_URI1 }}
  IMAGE_URI2: ${{ secrets.IMAGE_URI2 }}
  IMAGE_URI3: ${{ secrets.IMAGE_URI3 }}
  NET: ${{ secrets.NET }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn --ignore-scripts
        shell: bash
      - name: Create local node and deploy
        run: |
          yarn hardhat node &
          yarn hardhat run scripts/deploy.ts --network localhost
      - name: Run Tests
        run: yarn hardhat test